import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC = path.join(__dirname, 'public');
const DATA = path.join(__dirname, 'data');
const UPLOADS = path.join(__dirname, 'uploads');
fs.mkdirSync(DATA,{recursive:true}); fs.mkdirSync(UPLOADS,{recursive:true});
const db = new DatabaseSync(path.join(DATA,'consultoria.db'));
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT, role TEXT NOT NULL CHECK(role IN ('admin','student')), name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, whatsapp TEXT DEFAULT '', password_hash TEXT NOT NULL, active INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT DEFAULT '', whatsapp TEXT NOT NULL, instagram TEXT DEFAULT '', goal TEXT DEFAULT '', age TEXT DEFAULT '', height TEXT DEFAULT '', weight TEXT DEFAULT '', injuries TEXT DEFAULT '', conditions TEXT DEFAULT '', medications TEXT DEFAULT '', availability TEXT DEFAULT '', experience TEXT DEFAULT '', notes TEXT DEFAULT '', status TEXT DEFAULT 'Novo', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS clients(id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE, plan TEXT DEFAULT 'Consultoria Online', price REAL DEFAULT 0, start_date TEXT, next_due TEXT, status TEXT DEFAULT 'Ativo', objective TEXT DEFAULT '', observations TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE, amount REAL NOT NULL, due_date TEXT NOT NULL, status TEXT DEFAULT 'Pendente', method TEXT DEFAULT '', external_id TEXT DEFAULT '', paid_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS workouts(id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE, title TEXT NOT NULL, notes TEXT DEFAULT '', active INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS exercises(id INTEGER PRIMARY KEY AUTOINCREMENT, workout_id INTEGER NOT NULL REFERENCES workouts(id) ON DELETE CASCADE, name TEXT NOT NULL, sets TEXT DEFAULT '', reps TEXT DEFAULT '', load TEXT DEFAULT '', rest TEXT DEFAULT '', notes TEXT DEFAULT '', sort_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS checkins(id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE, weight REAL, waist REAL, adherence INTEGER, sleep INTEGER, energy INTEGER, pain TEXT DEFAULT '', notes TEXT DEFAULT '', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS photos(id INTEGER PRIMARY KEY AUTOINCREMENT, client_id INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE, label TEXT DEFAULT '', filename TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at INTEGER NOT NULL);
`);

function hashPassword(password, salt=crypto.randomBytes(16).toString('hex')) { const hash=crypto.scryptSync(password,salt,64).toString('hex'); return `${salt}:${hash}`; }
function verifyPassword(password, stored){ const [salt,hash]=stored.split(':'); if(!salt||!hash)return false; const test=crypto.scryptSync(password,salt,64); return crypto.timingSafeEqual(test,Buffer.from(hash,'hex')); }
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));}
function currentUser(req){ const token=cookies(req).session; if(!token)return null; const s=db.prepare('SELECT s.token,s.expires_at,u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=?').get(token); if(!s||s.expires_at<Date.now()||!s.active){if(s)db.prepare('DELETE FROM sessions WHERE token=?').run(token);return null;} return s; }
function send(res,status,body,type='application/json; charset=utf-8',headers={}){res.writeHead(status,{'Content-Type':type,...headers});res.end(type.startsWith('application/json')?JSON.stringify(body):body);}
function json(res,status,obj,headers={}){send(res,status,obj,'application/json; charset=utf-8',headers)}
async function body(req,limit=7_000_000){return await new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>limit){req.destroy();reject(new Error('Payload muito grande'));}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject);});}
function requireRole(req,res,role){const u=currentUser(req);if(!u){json(res,401,{error:'Não autenticado'});return null;}if(role&&u.role!==role){json(res,403,{error:'Sem permissão'});return null;}return u;}
function clientForUser(userId){return db.prepare('SELECT c.*,u.name,u.email,u.whatsapp FROM clients c JOIN users u ON u.id=c.user_id WHERE c.user_id=?').get(userId)}
function mime(file){const e=path.extname(file).toLowerCase();return ({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon'})[e]||'application/octet-stream'}
function serveStatic(req,res,pathname){let rel=pathname==='/'?'index.html':pathname.slice(1);let p=path.normalize(path.join(PUBLIC,rel));if(!p.startsWith(PUBLIC)||!fs.existsSync(p)||fs.statSync(p).isDirectory())return false;send(res,200,fs.readFileSync(p),mime(p));return true;}
function safeCsv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}

const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://localhost'); const p=url.pathname;
 if(p.startsWith('/uploads/')){const f=path.join(UPLOADS,path.basename(p));if(fs.existsSync(f))return send(res,200,fs.readFileSync(f),mime(f));return send(res,404,'');}
 if(req.method==='GET'&&p==='/api/setup/status') return json(res,200,{needsSetup:!db.prepare("SELECT 1 FROM users WHERE role='admin' LIMIT 1").get()});
 if(req.method==='POST'&&p==='/api/setup'){if(db.prepare("SELECT 1 FROM users WHERE role='admin' LIMIT 1").get())return json(res,409,{error:'Administrador já configurado'});const b=await body(req);if(!b.name||!b.email||!b.password||b.password.length<8)return json(res,400,{error:'Preencha nome, e-mail e senha com no mínimo 8 caracteres'});db.prepare("INSERT INTO users(role,name,email,password_hash) VALUES('admin',?,?,?)").run(b.name,b.email.toLowerCase(),hashPassword(b.password));return json(res,201,{ok:true});}
 if(req.method==='POST'&&p==='/api/login'){const b=await body(req);const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(String(b.email||'').toLowerCase());if(!u||!verifyPassword(b.password||'',u.password_hash))return json(res,401,{error:'E-mail ou senha inválidos'});const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').run(token,u.id,Date.now()+1000*60*60*24*7);return json(res,200,{ok:true,role:u.role,name:u.name},{'Set-Cookie':`session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`});}
 if(req.method==='POST'&&p==='/api/logout'){const token=cookies(req).session;if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(token);return json(res,200,{ok:true},{'Set-Cookie':'session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});}
 if(req.method==='GET'&&p==='/api/me'){const u=currentUser(req);return json(res,200,u?{authenticated:true,id:u.id,name:u.name,email:u.email,role:u.role}:{authenticated:false});}
 if(req.method==='POST'&&p==='/api/anamnese'){const b=await body(req);if(!b.name||!b.whatsapp)return json(res,400,{error:'Nome e WhatsApp são obrigatórios'});db.prepare(`INSERT INTO leads(name,email,whatsapp,instagram,goal,age,height,weight,injuries,conditions,medications,availability,experience,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b.name,b.email||'',b.whatsapp,b.instagram||'',b.goal||'',b.age||'',b.height||'',b.weight||'',b.injuries||'',b.conditions||'',b.medications||'',b.availability||'',b.experience||'',b.notes||'');return json(res,201,{ok:true,message:'Anamnese enviada com sucesso'});}

 if(p.startsWith('/api/admin/')){
  const admin=requireRole(req,res,'admin'); if(!admin)return;
  if(req.method==='GET'&&p==='/api/admin/dashboard'){const stats={leads:db.prepare('SELECT COUNT(*) n FROM leads').get().n,clients:db.prepare('SELECT COUNT(*) n FROM clients').get().n,active:db.prepare("SELECT COUNT(*) n FROM clients WHERE status='Ativo'").get().n,pending:db.prepare("SELECT COALESCE(SUM(amount),0) v FROM payments WHERE status='Pendente'").get().v,paid:db.prepare("SELECT COALESCE(SUM(amount),0) v FROM payments WHERE status='Pago'").get().v};return json(res,200,stats);}
  if(req.method==='GET'&&p==='/api/admin/leads')return json(res,200,db.prepare('SELECT * FROM leads ORDER BY id DESC').all());
  if(req.method==='GET'&&p==='/api/admin/clients')return json(res,200,db.prepare(`SELECT c.*,u.name,u.email,u.whatsapp,(SELECT status FROM payments p WHERE p.client_id=c.id ORDER BY due_date DESC LIMIT 1) payment_status FROM clients c JOIN users u ON u.id=c.user_id ORDER BY c.id DESC`).all());
  if(req.method==='POST'&&p==='/api/admin/clients'){const b=await body(req);if(!b.name||!b.email||!b.password)return json(res,400,{error:'Nome, e-mail e senha temporária são obrigatórios'});try{db.exec('BEGIN');const r=db.prepare("INSERT INTO users(role,name,email,whatsapp,password_hash) VALUES('student',?,?,?,?)").run(b.name,b.email.toLowerCase(),b.whatsapp||'',hashPassword(b.password));const cnew=db.prepare('INSERT INTO clients(user_id,plan,price,start_date,next_due,status,objective,observations) VALUES(?,?,?,?,?,?,?,?)').run(r.lastInsertRowid,b.plan||'Consultoria Online',Number(b.price||0),b.start_date||new Date().toISOString().slice(0,10),b.next_due||'',b.status||'Ativo',b.objective||'',b.observations||'');if(b.next_due&&Number(b.price)>0)db.prepare('INSERT INTO payments(client_id,amount,due_date,status) VALUES(?,?,?,?)').run(cnew.lastInsertRowid,Number(b.price),b.next_due,'Pendente');db.exec('COMMIT');return json(res,201,{ok:true,id:Number(cnew.lastInsertRowid)});}catch(e){try{db.exec('ROLLBACK')}catch{}return json(res,400,{error:e.message.includes('UNIQUE')?'E-mail já cadastrado':e.message});}}
  const mClient=p.match(/^\/api\/admin\/clients\/(\d+)$/);if(mClient&&req.method==='PATCH'){const b=await body(req);const id=Number(mClient[1]);const c=db.prepare('SELECT * FROM clients WHERE id=?').get(id);if(!c)return json(res,404,{error:'Cliente não encontrado'});db.prepare('UPDATE clients SET plan=?,price=?,next_due=?,status=?,objective=?,observations=? WHERE id=?').run(b.plan??c.plan,Number(b.price??c.price),b.next_due??c.next_due,b.status??c.status,b.objective??c.objective,b.observations??c.observations,id);return json(res,200,{ok:true});}
  if(req.method==='POST'&&p==='/api/admin/payments'){const b=await body(req);db.prepare('INSERT INTO payments(client_id,amount,due_date,status,method) VALUES(?,?,?,?,?)').run(Number(b.client_id),Number(b.amount),b.due_date,b.status||'Pendente',b.method||'');return json(res,201,{ok:true});}
  const mPay=p.match(/^\/api\/admin\/payments\/(\d+)$/);if(mPay&&req.method==='PATCH'){const b=await body(req);const st=b.status||'Pendente';db.prepare('UPDATE payments SET status=?,method=?,paid_at=? WHERE id=?').run(st,b.method||'',st==='Pago'?new Date().toISOString():null,Number(mPay[1]));return json(res,200,{ok:true});}
  if(req.method==='GET'&&p==='/api/admin/payments')return json(res,200,db.prepare(`SELECT p.*,u.name FROM payments p JOIN clients c ON c.id=p.client_id JOIN users u ON u.id=c.user_id ORDER BY p.due_date DESC`).all());
  if(req.method==='POST'&&p==='/api/admin/workouts'){const b=await body(req);try{db.exec('BEGIN');const w=db.prepare('INSERT INTO workouts(client_id,title,notes,active) VALUES(?,?,?,1)').run(Number(b.client_id),b.title,b.notes||'');const st=db.prepare('INSERT INTO exercises(workout_id,name,sets,reps,load,rest,notes,sort_order) VALUES(?,?,?,?,?,?,?,?)');(b.exercises||[]).forEach((e,i)=>st.run(w.lastInsertRowid,e.name,e.sets||'',e.reps||'',e.load||'',e.rest||'',e.notes||'',i));db.exec('COMMIT');return json(res,201,{ok:true,id:Number(w.lastInsertRowid)});}catch(e){try{db.exec('ROLLBACK')}catch{}return json(res,400,{error:e.message});}}
  if(req.method==='GET'&&p==='/api/admin/workouts'){return json(res,200,db.prepare(`SELECT w.*,u.name FROM workouts w JOIN clients c ON c.id=w.client_id JOIN users u ON u.id=c.user_id ORDER BY w.id DESC`).all());}
  if(req.method==='GET'&&p==='/api/admin/checkins'){return json(res,200,db.prepare(`SELECT ch.*,u.name FROM checkins ch JOIN clients c ON c.id=ch.client_id JOIN users u ON u.id=c.user_id ORDER BY ch.id DESC`).all());}
  if(req.method==='GET'&&p==='/api/admin/export.csv'){const rows=db.prepare(`SELECT c.id,u.name,u.email,u.whatsapp,c.status,c.objective,c.plan,c.price,c.start_date,c.next_due,c.observations FROM clients c JOIN users u ON u.id=c.user_id ORDER BY c.id`).all();const keys=['id','name','email','whatsapp','status','objective','plan','price','start_date','next_due','observations'];const csv=[keys.join(','),...rows.map(r=>keys.map(k=>safeCsv(r[k])).join(','))].join('\n');return send(res,200,csv,'text/csv; charset=utf-8',{'Content-Disposition':'attachment; filename="crm_artur_lima.csv"'});}
 }

 if(p.startsWith('/api/student/')){
  const u=requireRole(req,res,'student');if(!u)return;const c=clientForUser(u.id);if(!c)return json(res,404,{error:'Cadastro de cliente não encontrado'});
  if(req.method==='GET'&&p==='/api/student/dashboard'){const payment=db.prepare('SELECT * FROM payments WHERE client_id=? ORDER BY due_date DESC LIMIT 1').get(c.id)||null;const workout=db.prepare('SELECT * FROM workouts WHERE client_id=? AND active=1 ORDER BY id DESC LIMIT 1').get(c.id)||null;const last=db.prepare('SELECT * FROM checkins WHERE client_id=? ORDER BY id DESC LIMIT 1').get(c.id)||null;return json(res,200,{client:c,payment,workout,lastCheckin:last});}
  if(req.method==='GET'&&p==='/api/student/workouts'){const ws=db.prepare('SELECT * FROM workouts WHERE client_id=? AND active=1 ORDER BY id DESC').all(c.id);for(const w of ws)w.exercises=db.prepare('SELECT * FROM exercises WHERE workout_id=? ORDER BY sort_order,id').all(w.id);return json(res,200,ws);}
  if(req.method==='POST'&&p==='/api/student/checkins'){const b=await body(req);db.prepare('INSERT INTO checkins(client_id,weight,waist,adherence,sleep,energy,pain,notes) VALUES(?,?,?,?,?,?,?,?)').run(c.id,b.weight||null,b.waist||null,b.adherence||null,b.sleep||null,b.energy||null,b.pain||'',b.notes||'');return json(res,201,{ok:true});}
  if(req.method==='GET'&&p==='/api/student/checkins')return json(res,200,db.prepare('SELECT * FROM checkins WHERE client_id=? ORDER BY id DESC').all(c.id));
  if(req.method==='POST'&&p==='/api/student/photos'){const b=await body(req);const m=String(b.data||'').match(/^data:image\/(jpeg|png|webp);base64,(.+)$/);if(!m)return json(res,400,{error:'Imagem inválida'});const buf=Buffer.from(m[2],'base64');if(buf.length>5_000_000)return json(res,400,{error:'Imagem acima de 5 MB'});const ext=m[1]==='jpeg'?'jpg':m[1];const name=`${c.id}-${Date.now()}-${crypto.randomBytes(4).toString('hex')}.${ext}`;fs.writeFileSync(path.join(UPLOADS,name),buf);db.prepare('INSERT INTO photos(client_id,label,filename) VALUES(?,?,?)').run(c.id,b.label||'',name);return json(res,201,{ok:true});}
  if(req.method==='GET'&&p==='/api/student/photos'){return json(res,200,db.prepare("SELECT id,label,'/uploads/'||filename url,created_at FROM photos WHERE client_id=? ORDER BY id DESC").all(c.id));}
  if(req.method==='GET'&&p==='/api/student/payments')return json(res,200,db.prepare('SELECT * FROM payments WHERE client_id=? ORDER BY due_date DESC').all(c.id));
  if(req.method==='POST'&&p==='/api/student/checkout')return json(res,501,{error:'Gateway ainda não conectado. Configure Mercado Pago/Stripe/PagSeguro no backend para gerar Pix ou cartão real.'});
 }

 if(serveStatic(req,res,p))return; send(res,404,'Não encontrado','text/plain; charset=utf-8');
}catch(e){console.error(e);json(res,500,{error:'Erro interno',detail:process.env.NODE_ENV==='development'?e.message:undefined});}});
const PORT=Number(process.env.PORT||3000);server.listen(PORT,()=>console.log(`Consultoria Artur Lima em http://localhost:${PORT}`));
